export const FETCH_ANESTHESIOLOGISTS = 'FETCH_ANESTHESIOLOGISTS';
export const ADD_ANESTHESIOLOGIST = 'ADD_ANESTHESIOLOGIST';
export const SET_SCHEDULES = 'SET_SCHEDULES';
export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
